name: "godot-ci export"
on:
  push:
    branches:
      - master

env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: cat_hero

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          #cd $EXPORT_NAME
          godot -v --export "HTML5" build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web

  deploy-to-page:
    name: Deploy to GitHub Page
    needs: export-web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: web
          path: web
      - name: display
        run:
          ls -la
          #cat ${{ secrets.PAGE_DEPLOY_KEY }}
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          ssh-key: ${{ secrets.PAGE_DEPLOY_KEY }}
          #github_token: ${{ secrets.PAGE_T }}
          repository-name: tzwm/cat_hero_pages
          branch: gh-pages # The branch the action should deploy to.
          folder: web # The folder the action should deploy.
